name: Go

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: hash commit
        run: echo ${GITHUB_SHA::7}
      - name: change env
        run: |
          cd configs
          echo "APP_VERSION=${GITHUB_SHA::7}" >> .env
          cat .env

